# You can change these
url: http://addama.github.io/sop
repo: https://github.com/addama/sop
title: Development Standards of Practice

# You should not change these
plugins:
 - jekyll-mentions
 - jemoji

permalink: /:categories/:title
highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: highlight
    default_lang: js
    span:
      disable: false
    block:
      line_numbers: true
      start_line: 1
keep_files: [ images ]